name: "Create Automatic Release after tag created"
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Generate jar with all dependencies
        run: ./gradlew build
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          prerelease: false
          files: |
            ./app/build/libs/*.jar
            continue-on-error: true
      - name: "Check if release already exist"
        if: steps.release.resource == 'Release' && steps.release.code == 'already_exists' && steps.release.field == 'tag_name'
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          files: ./app/build/libs/*all.jar
      - name: 'Remove Snapshots Before Caching'
        run: find ./app/build/libs/ -name *.jar | xargs rm -Rf
