name: "Deploy to the Server"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: RELEASE VERSION
        run: echo  "tag Name is ${{ steps.tagName.outputs.tag }}"
        shell: pwsh
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: setup rsync
        uses: GuillaumeFalourd/setup-rsync@v1
      - name: check rsync version
        run: rsync --help
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          if_key_exists: replace
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz --rsync-path="mkdir -p ${{ secrets.DEPLOY_PATH}}${{ steps.tagName.outputs.tag }} && rsync" ./app/build/libs/*all.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH}}${{ steps.tagName.outputs.tag }}
