name: "Prepare for next release"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  svcheck:
    name: semantic version check
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.releaseType.outputs.release_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Get previous tag version
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag
        with:
          fallback: 1.0.0
      - name: Compare semantic version
        uses: tj-actions/semver-diff@v2.0.0
        id: comparesv
      - name: Compare version
        run: echo "Compare result is ${{ steps.comparesv.outputs.release_type }}"
      - name: Check if minor, patch, prelease or build release
        id: releaseType
        if: (${{ steps.comparesv.outputs.release_type }} != major || ${{ steps.tagName.outputs.tag }} == ${{ steps.previoustag.outputs.tag }})
        run: echo "::set-output name=release_type::${{ steps.comparesv.outputs.release_type }}"

  next-release:
    name: Next release prepare
    needs: svcheck
    runs-on: ubuntu-latest
    if: needs.svcheck.outputs.release_type == 'major'
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Prepare for next release
        run: ./gradlew incrementSemanticVersion --major
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          commit-message: Prepare for next release
          branch: next-release-prepare
          delete-branch: true
          title: Prepare for next release
          draft: false
          base: master
